use `akura`;
/*!40014 SET UNIQUE_CHECKS=0 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

--
-- Table structure for table `FAITH_LIFE_RATING`
--
ALTER TABLE `FAITH_LIFE_RATING` CHANGE COLUMN `FAITH_LIFE_DESCRIPTION` `FAITH_LIFE_DESCRIPTION` VARCHAR(100) NULL DEFAULT NULL;

--
-- 'DAILY_STUDENT_ATTENDENCE' Tables' `DAILY_STUDENT_ATTENDANCE_ID` column, change to AUTO_INCREMENT
--
ALTER TABLE `DAILY_STUDENT_ATTENDANCE` CHANGE COLUMN `DAILY_STUDENT_ATTENDANCE_ID` `DAILY_STUDENT_ATTENDANCE_ID` INT(11) NOT NULL AUTO_INCREMENT;

--
-- 'DAILY_TEACHER_ATTENDANCE' Tables' `DAILY_TEACHER_ATTENDANCE_ID` column, change to AUTO_INCREMENT
--
ALTER TABLE `DAILY_TEACHER_ATTENDANCE` CHANGE COLUMN `DAILY_TEACHER_ATTENDANCE_ID` `DAILY_TEACHER_ATTENDANCE_ID` INT(11) NOT NULL AUTO_INCREMENT;

/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40014 SET UNIQUE_CHECKS=1 */;