\. akura2.6/AKURA_TABLES.sql
\. akura2.6/AKURA_VIEWS.sql
\. akura2.6/SP_STUDENT_GAMIFICATION_SEARCH.sql
\. akura2.6/AKURA_STUDENT_ADVANCE_SEARCH_SP.sql
\. akura2.6/AKURA_DEFAULT_DATA_USER_PRVILEGES.sql
\. akura2.6/AKURA_DEFAULT_DATA.sql
