\. akura2.0/AKURA_TABLES.sql
\. akura2.0/AKURA_VIEWS.sql
\. akura2.0/AKURA_DEFAULT_DATA.sql
\. akura2.0/SMS_STUDENT_ADVANCE_SEARCH_SP.sql
\. akura2.0/SP_STUDENT_EXAM_MARK.sql
\. akura2.0/SP_LANGUAGE_ID_TO_STUDY_MEDIUM_MIGRATION.sql
\. akura2.0/AKURA_DEFAULT_DATA_USER_PRVILEGES.sql