/*
 * < �KURA, This application manages the daily activities of a Teacher and a Student of a School>
 *
 * Copyright (C) 2012 Virtusa Corporation.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

package com.virtusa.akura.api.dto;

import java.util.Date;

/**
 * This class is to associates all the properties of StudentLeave domain object.
 * 
 * @author Virtusa Corporation
 */
public class StudentLeave extends BaseDomain {
    
    /** Holds serial version id. */
    private static final long serialVersionUID = 1L;
    
    /** Represents the status of the medical certificate. */
    private int noOfDays;

    /** key to hold string toDate. */
    private static final String TO_DATE = ", toDate=";
    
    /** key to hold string fromDate. */
    private static final String FROM_DATE = ", fromDate=";
    
    /** key to hold string reason. */
    private static final String REASON = ", reason=";
    
    /** key to hold string studentId. */
    private static final String STUDENT_ID = ", studentId=";
    
    /** key to hold string studentLeaveId. */
    private static final String STUDENT_LEAVE_ID = "studentLeaveId=";
    
    /** Holds student level id for StudentLeave object. */
    private int studentLeaveId;
    
    /** Holds student id for StudentLeave object. */
    private int studentId;
    
    /** Holds reason for StudentLeave object. */
    private String reason;
    
    /** Holds fromDate for StudentLeave object. */
    private Date fromDate;
    
    /** Holds toDate for StudentLeave object. */
    private Date toDate;
    
    /** Holds autoGenerated Status for StudentLeave object. */
    private boolean checkAutoGenerated;
    
    
    /**
     * Returns the checkAutoGenerated.
     * @return - checkAutoGenerated.
     */
    public boolean isCheckAutoGenerated() {
    
        return checkAutoGenerated;
    }

    /**
     * Sets the checkAutoGenerated.
     * @param checkAutoGeneratedVal - boolean.
     */
    public void setCheckAutoGenerated(boolean checkAutoGeneratedVal) {
    
        this.checkAutoGenerated = checkAutoGeneratedVal;
    }

    /**
     * Represents the status of the medical certificate.
     */
    private boolean certificategiven;
    
    /**
     * Returns the number of leave days.
     * @return - the number of leave days.
     */
    public int getNoOfDays() {

        return noOfDays;
    }

    /**
     * Sets the number of leave days.
     * @param intNoOfDays - the number of leave days.
     */
    public void setNoOfDays(int intNoOfDays) {

        this.noOfDays = intNoOfDays;
    }

    /**
     * Returns the status of the medical certificate.
     * 
     * @return - the status of the medical certificate.
     */
    public boolean getCertificategiven() {
    
        return certificategiven;
    }
    
    /**
     * Sets the status of the medical certificate.
     * 
     * @param bCertificategiven - the status of the medical certificate.
     */
    public void setCertificategiven(final boolean bCertificategiven) {
    
        this.certificategiven = bCertificategiven;
    }
    
    /**
     * Get the student leave id for the StudentLeave.
     * 
     * @return the studentLeaveId
     */
    public int getStudentLeaveId() {
    
        return studentLeaveId;
    }
    
    /**
     * Set the student leave id for the StudentLeave.
     * 
     * @param studentLeaveIdValue the studentLeaveId to set
     */
    public void setStudentLeaveId(int studentLeaveIdValue) {
    
        this.studentLeaveId = studentLeaveIdValue;
    }
    
    /**
     * Get the student id for the StudentLeave.
     * 
     * @return the studentId
     */
    public int getStudentId() {
    
        return studentId;
    }
    
    /**
     * Set the student id for the StudentLeave.
     * 
     * @param studentIdValue the studentId to set
     */
    public void setStudentId(int studentIdValue) {
    
        this.studentId = studentIdValue;
    }
    
    /**
     * Get the reason for the StudentLeave.
     * 
     * @return the reason
     */
    public String getReason() {
    
        return reason;
    }
    
    /**
     * Set the reason for the StudentLeave.
     * 
     * @param reasonValue the reason to set
     */
    public void setReason(String reasonValue) {
    
        this.reason = reasonValue;
    }
    
    /**
     * Get the start date for the student leave.
     * 
     * @return the fromDate
     */
    public Date getFromDate() {
    
        if (fromDate != null) {
            return (Date) fromDate.clone();
        }
        return null;
    }
    
    /**
     * Set the start date of the student leave.
     * 
     * @param fromDateValue the fromDate to set
     */
    public void setFromDate(Date fromDateValue) {
    
        if (fromDateValue != null) {
            this.fromDate = (Date) fromDateValue.clone();
        }
    }
    
    /**
     * Get the end date for the student leave.
     * 
     * @return the toDate
     */
    public Date getToDate() {
    
        if (toDate != null) {
            return (Date) toDate.clone();
        }
        return null;
    }
    
    /**
     * Set the end date for the student leave.
     * 
     * @param toDateValue the toDate to set
     */
    public void setToDate(Date toDateValue) {
    
        if (toDateValue != null) {
            this.toDate = (Date) toDateValue.clone();
        }
    }
    
    /**
     * Returns a string representation of the object.
     * 
     * @return - the current object details.
     */
    @Override
    public String toString() {
    
        return STUDENT_LEAVE_ID + studentLeaveId + STUDENT_ID + studentId + REASON + reason + FROM_DATE + fromDate
                + TO_DATE + toDate;
    }
}
