\. akura2.4/STUDENT_STATUS_FIX.sql
\. akura2.4/STAFF_LEAVE_TYPE_INTEGRATION.sql
\. akura2.4/AKURA_TABLES.sql
\. akura2.4/AKURA_VIEWS.sql
\. akura2.4/AKURA_DEFAULT_DATA_USER_PRVILEGES.sql
\. akura2.4/AKURA_STUDENT_ADVANCE_SEARCH_SP.sql
\. akura2.4/SP_STUDENT_EXAM_MARK.sql
\. akura2.4/AKURA_DEFAULT_DATA.sql
\. akura2.4/METHOD_OF_TRAVEL_FIX.sql

