use `akura`;

INSERT INTO `GRADING` (`DESCRIPTION`,`GRADE_ACRONYM`,`MODIFIED_TIME`) VALUES 
('test','X','2011-09-06 15:20:36');

UPDATE `FAITH_LIFE_RATING` SET GRADING_ID = 
(SELECT MAX(GRADING_ID) FROM GRADING WHERE GRADE_ACRONYM ='X')
where GRADING_ID = 0;
